[project]
name = "hw4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
